arb-dir: lib/l10n
template-arb-file: app_zh.arb
output-localization-file: wan_android_localizations.dart
output-class: WanAndroidLocalizations
preferred-supported-locales:
  - en
  - zh
use-deferred-loading: true